spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms
    username: lms
    password: zb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.kdomo@gmail.com
    password: tjhijuzmwnnyngaq
    properties:
      mail:
        smtp:
          starttls:
            enable: true

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl